require.config({
	baseUrl:"/",
	paths:{
		"jquery":"lib/jquery/jquery-3.2.1",
		"Swiper":"lib/swiper/js/swiper",
		"header":"js/module/header",
		"footer":"js/module/footer",
		"url":"js/module/url",
		"template":"lib/art-template/template-web"
	}
})